#!/bin/bash
# Setup guide for Cashfree payment integration

echo "🚀 Zoyka Cashfree Payment Setup"
echo "================================"
echo ""
echo "Follow these steps to enable payment processing:"
echo ""
echo "1️⃣  Register with Cashfree:"
echo "   - Visit: https://dashboard.cashfree.com"
echo "   - Sign up as merchant"
echo "   - Complete KYC verification"
echo ""
echo "2️⃣  Get API Credentials:"
echo "   - Go to: Settings → API Keys"
echo "   - Copy App ID (x-client-id)"
echo "   - Copy Secret Key (x-client-secret)"
echo ""
echo "3️⃣  Update .env file:"
echo "   - Open: .env"
echo "   - Replace CASHFREE_APP_ID with your App ID"
echo "   - Replace CASHFREE_SECRET_KEY with your Secret Key"
echo "   - Set CASHFREE_ENVIRONMENT to 'sandbox' for testing"
echo ""
echo "4️⃣  Configure Webhook in Cashfree Dashboard:"
echo "   - Settings → Webhooks"
echo "   - Add URL: http://localhost:3001/api/payments/webhook/payment"
echo "   - Select events: PAYMENT_SUCCESS, PAYMENT_FAILED, PAYMENT_CANCELLED"
echo "   - Save and test"
echo ""
echo "5️⃣  Test the integration:"
echo "   - npm run dev (start backend)"
echo "   - npm run dev (start frontend on port 5173)"
echo "   - Add products to cart"
echo "   - Checkout with test card: 4111 1111 1111 1111"
echo "   - Verify order appears in My Orders"
echo ""
echo "📚 For detailed setup, see: PAYMENT_SETUP.md"
echo ""
